#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BENCH_DIR="$SCRIPT_DIR/frappe-bench"
APPS_SRC="${APPS_SRC:-$SCRIPT_DIR/apps}"
LOG_DIR="$SCRIPT_DIR/logs/site_setup"
RUN_LOG="$LOG_DIR/site-setup-$(date +%Y%m%d-%H%M%S).log"
BENCH_LOG_DIR="$SCRIPT_DIR/logs/bench"
BENCH_LOG="$BENCH_LOG_DIR/bench-start.log"
NODE_MAJOR="${NODE_MAJOR:-}"
FRAPPE_BRANCH="${FRAPPE_BRANCH:-version-15}"
SECRETS_DIR="$SCRIPT_DIR/.secrets"
SECRETS_SITES_DIR="$SECRETS_DIR/sites"
SECRETS_INDEX="$SECRETS_DIR/sites.env"
SECRETS_NOTES="$SECRETS_DIR/notes.md"
LEGACY_SECRETS_FILE="$SCRIPT_DIR/secrets.md"

export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
export NVM_DIR="$HOME/.nvm"

SUDO=()
ADMIN_PASSWORD=""
ADMIN_PASSWORD_SOURCE=""

mkdir -p "$LOG_DIR"
exec > >(tee -a "$RUN_LOG") 2>&1

info() { printf '[INFO] %s\n' "$*"; }
warn() { printf '[WARN] %s\n' "$*" >&2; }
err() { printf '[ERROR] %s\n' "$*" >&2; }
ok() { printf '[OK] %s\n' "$*"; }
die() { err "$*"; exit 1; }

trap 'err "Failed at line $LINENO: $BASH_COMMAND"' ERR

section() {
  printf '\n'
  printf '==================================================\n'
  printf ' %s\n' "$*"
  printf '==================================================\n'
}

run() {
  info "[RUN] $*"
  "$@"
}

have_cmd() {
  command -v "$1" >/dev/null 2>&1
}

now_iso() {
  date '+%Y-%m-%d %H:%M:%S %z'
}

join_by() {
  local sep="$1"
  shift || true
  local out="" item
  for item in "$@"; do
    if [[ -z "$out" ]]; then
      out="$item"
    else
      out="$out$sep$item"
    fi
  done
  printf '%s' "${out:-none}"
}

shell_quote() {
  local value="$1"
  printf "'%s'" "$(printf "%s" "$value" | sed "s/'/'\\''/g")"
}

safe_secret_filename() {
  local site="$1"
  printf "%s" "$site" | sed 's/[^A-Za-z0-9._-]/_/g'
}

site_secret_path() {
  local site="$1"
  printf "%s/%s.env" "$SECRETS_SITES_DIR" "$(safe_secret_filename "$site")"
}

ensure_secrets_file() {
  mkdir -p "$SECRETS_SITES_DIR"

  if [[ ! -f "$SECRETS_INDEX" ]]; then
    {
      printf '# Frappe Local Site Secrets Index\n'
      printf '# Generated by site_setup.sh. Do not commit this folder.\n'
      printf '# Bench path: %s\n' "$BENCH_DIR"
      printf '# Frappe branch: %s\n' "$FRAPPE_BRANCH"
      printf '# Created at: %s\n\n' "$(now_iso)"
    } >"$SECRETS_INDEX"
  fi

  if [[ ! -f "$SECRETS_NOTES" ]]; then
    {
      printf '# Frappe Local Setup Notes\n\n'
      printf 'Generated by scripts in this folder.\n'
    } >"$SECRETS_NOTES"
  fi

  chmod 700 "$SECRETS_DIR" "$SECRETS_SITES_DIR" 2>/dev/null || true
  chmod 600 "$SECRETS_INDEX" "$SECRETS_NOTES" 2>/dev/null || true
}

rebuild_sites_index() {
  ensure_secrets_file

  local tmp secret site
  tmp="$(mktemp -t frappe-sites-index.XXXXXX)"

  {
    printf '# Frappe Local Site Secrets Index\n'
    printf '# Generated by site_setup.sh. Do not commit this folder.\n'
    printf '# Bench path: %s\n' "$BENCH_DIR"
    printf '# Frappe branch: %s\n' "$FRAPPE_BRANCH"
    printf '# Updated at: %s\n\n' "$(now_iso)"
  } >"$tmp"

  for secret in "$SECRETS_SITES_DIR"/*.env; do
    [[ -f "$secret" ]] || continue
    site="$(awk -F= '$1 == "SITE_NAME" {gsub(/^'''|'''$/, "", $2); print $2; exit}' "$secret" 2>/dev/null || true)"
    [[ -n "$site" ]] || site="$(basename "$secret" .env)"
    printf 'SITE_SECRET_%s=%s\n' "$(safe_secret_filename "$site" | tr '.-' '__')" "$(shell_quote "$secret")" >>"$tmp"
  done

  mv "$tmp" "$SECRETS_INDEX"
  chmod 600 "$SECRETS_INDEX" 2>/dev/null || true
}

append_site_secret() {
  local site="$1"
  local admin_password="$2"
  local admin_password_source="$3"
  local db_name="$4"
  local db_password="$5"
  local db_password_source="$6"
  local apps="$7"
  local secret_file

  ensure_secrets_file
  secret_file="$(site_secret_path "$site")"

  {
    printf '# Frappe Local Site Secret\n'
    printf '# Generated by site_setup.sh. Do not commit this file.\n'
    printf 'SITE_NAME=%s\n' "$(shell_quote "$site")"
    printf 'SITE_URL=%s\n' "$(shell_quote "http://$site:8000")"
    printf 'ADMIN_USER=%s\n' "$(shell_quote "Administrator")"
    printf 'ADMIN_PASSWORD=%s\n' "$(shell_quote "$admin_password")"
    printf 'ADMIN_PASSWORD_SOURCE=%s\n' "$(shell_quote "$admin_password_source")"
    printf 'DB_NAME=%s\n' "$(shell_quote "$db_name")"
    printf 'DB_USER=%s\n' "$(shell_quote "$db_name")"
    printf 'DB_PASSWORD=%s\n' "$(shell_quote "$db_password")"
    printf 'DB_PASSWORD_SOURCE=%s\n' "$(shell_quote "$db_password_source")"
    printf 'INSTALLED_APPS=%s\n' "$(shell_quote "$apps")"
    printf 'BENCH_DIR=%s\n' "$(shell_quote "$BENCH_DIR")"
    printf 'FRAPPE_BRANCH=%s\n' "$(shell_quote "$FRAPPE_BRANCH")"
    printf 'CREATED_AT=%s\n' "$(shell_quote "$(now_iso)")"
  } >"$secret_file"

  chmod 600 "$secret_file" 2>/dev/null || true
  rebuild_sites_index
  ok "site credentials saved: $secret_file"

  if [[ -f "$LEGACY_SECRETS_FILE" ]]; then
    warn "legacy secrets.md still exists. New credentials are now stored in .secrets/sites/"
  fi
}

remove_site_secret() {
  local site="$1"
  local secret_file
  secret_file="$(site_secret_path "$site")"

  ensure_secrets_file

  if [[ -f "$secret_file" ]]; then
    rm -f "$secret_file"
    ok "removed site secret: $secret_file"
  else
    warn "site secret not found, nothing to remove: $secret_file"
  fi

  rebuild_sites_index
}

append_note_secret() {
  local title="$1"
  shift || true
  local line

  ensure_secrets_file
  {
    printf '\n## Note: %s\n' "$title"
    printf -- '- Timestamp: %s\n' "$(now_iso)"
    for line in "$@"; do
      printf -- '- %s\n' "$line"
    done
  } >>"$SECRETS_NOTES"
  chmod 600 "$SECRETS_NOTES" 2>/dev/null || true
}

repair_secrets() {
  section "Repair Secrets"
  validate_runtime
  ensure_secrets_file

  local secret site stale=0 missing=0
  for secret in "$SECRETS_SITES_DIR"/*.env; do
    [[ -f "$secret" ]] || continue
    site="$(awk -F= '$1 == "SITE_NAME" {gsub(/^'''|'''$/, "", $2); print $2; exit}' "$secret" 2>/dev/null || true)"
    [[ -n "$site" ]] || site="$(basename "$secret" .env)"

    if [[ ! -d "$BENCH_DIR/sites/$site" ]]; then
      warn "stale secret found for missing site: $site"
      if confirm_remove_stale_secret "$site" "$secret"; then
        rm -f "$secret"
        ok "removed stale secret: $secret"
        stale=$((stale + 1))
      fi
    fi
  done

  while IFS= read -r site; do
    [[ -n "$site" ]] || continue
    secret="$(site_secret_path "$site")"
    if [[ ! -f "$secret" ]]; then
      warn "site exists but secret is missing: $site"
      missing=$((missing + 1))
    fi
  done < <(site_names)

  rebuild_sites_index
  ok "secrets repair complete. Removed stale: $stale. Missing secrets: $missing"
}

confirm_remove_stale_secret() {
  local site="$1"
  local secret="$2"
  local answer
  read -r -p "Remove stale secret for $site? y/N: " answer
  case "${answer:-}" in
    y|Y|yes|YES)
      return 0
      ;;
    *)
      warn "kept stale secret: $secret"
      return 1
      ;;
  esac
}

refresh_path() {
  export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
  export NVM_DIR="$HOME/.nvm"

  if [[ -s "$NVM_DIR/nvm.sh" ]]; then
    # shellcheck disable=SC1091
    . "$NVM_DIR/nvm.sh"

    if [[ -n "${NODE_MAJOR:-}" ]]; then
      nvm use "$NODE_MAJOR" >/dev/null 2>&1 || true
    elif [[ -f "$NVM_DIR/alias/default" ]]; then
      nvm use default >/dev/null 2>&1 || true
    fi
  fi
}

need_sudo() {
  if [[ "${EUID:-$(id -u)}" -eq 0 ]]; then
    SUDO=()
    return 0
  fi
  have_cmd sudo || return 1
  sudo -v || return 1
  SUDO=(sudo)
}

valid_bench() {
  [[ -d "$BENCH_DIR/apps/frappe" ]] || return 1
  [[ -d "$BENCH_DIR/sites" ]] || return 1
  [[ -x "$BENCH_DIR/env/bin/python" ]] || return 1
  [[ -f "$BENCH_DIR/Procfile" ]] || return 1
  [[ -f "$BENCH_DIR/sites/common_site_config.json" ]] || return 1
  return 0
}

validate_runtime() {
  refresh_path
  valid_bench || die "valid bench not found: $BENCH_DIR"
  have_cmd bench || die "bench command not found. Run ./install.sh first."
  have_cmd node || die "node command not found. Run ./install.sh first."
  have_cmd yarn || die "yarn command not found. Run ./install.sh first."

  info "runtime node: $(node -v 2>/dev/null || true)"
  info "runtime yarn: $(yarn --version 2>/dev/null || true)"
}

bench_run() {
  validate_runtime
  info "[RUN] bench $*"
  (cd "$BENCH_DIR" && bench "$@")
}

common_config_value() {
  local key="$1"
  local config="$BENCH_DIR/sites/common_site_config.json"
  [[ -f "$config" ]] || return 1
  "$BENCH_DIR/env/bin/python" -c 'import json, sys
with open(sys.argv[1], encoding="utf-8") as f:
    data = json.load(f)
value = data.get(sys.argv[2], "")
print("" if value is None else value)
' "$config" "$key"
}

redis_cache_port() {
  local url port
  url="$(common_config_value redis_cache 2>/dev/null || true)"
  [[ -n "$url" ]] || return 1
  port="$("$BENCH_DIR/env/bin/python" -c 'from urllib.parse import urlparse
import sys
parsed = urlparse(sys.argv[1])
print(parsed.port or "")
' "$url")"
  [[ -n "$port" ]] || return 1
  printf '%s\n' "$port"
}

port_open() {
  local host="$1"
  local port="$2"
  timeout 2 bash -c ":</dev/tcp/$host/$port" >/dev/null 2>&1
}

redis_cache_running() {
  local port
  port="$(redis_cache_port 2>/dev/null || true)"
  [[ -n "$port" ]] || return 1
  port_open 127.0.0.1 "$port"
}

bench_pid_running() {
  local pid_file="$BENCH_DIR/.runner/bench_start.pid"
  local pid
  [[ -f "$pid_file" ]] || return 1
  pid="$(cat "$pid_file" 2>/dev/null || true)"
  [[ "$pid" =~ ^[0-9]+$ ]] || return 1
  kill -0 "$pid" >/dev/null 2>&1
}

ensure_bench_dev_services() {
  validate_runtime
  mkdir -p "$BENCH_DIR/.runner" "$BENCH_LOG_DIR"

  if redis_cache_running; then
    info "bench Redis cache service already reachable"
    return 0
  fi

  if bench_pid_running; then
    info "bench start is already tracked; waiting for Redis cache"
  else
    info "starting bench services in background for app install/migrate"
    (
      cd "$BENCH_DIR"
      nohup setsid bench start >>"$BENCH_LOG" 2>&1 &
      printf '%s\n' "$!" >"$BENCH_DIR/.runner/bench_start.pid"
    )
    info "bench background log: $BENCH_LOG"
  fi

  local attempt
  for attempt in {1..20}; do
    if redis_cache_running; then
      ok "bench Redis cache service is running"
      return 0
    fi
    sleep 1
  done

  warn "bench Redis cache did not become reachable; log: $BENCH_LOG"
  return 1
}

site_names() {
  [[ -d "$BENCH_DIR/sites" ]] || return 0
  find "$BENCH_DIR/sites" -mindepth 1 -maxdepth 1 -type d \
    ! -name assets ! -name archived \
    -exec test -f "{}/site_config.json" \; -printf "%f\n" 2>/dev/null | sort
}

app_name_from_dir() {
  basename "$1"
}

is_system_app() {
  case "$1" in
    frappe|erpnext|payments|hrms|print_designer) return 0 ;;
    *) return 1 ;;
  esac
}

valid_custom_app_dir() {
  local dir="$1"
  local hook
  [[ -d "$dir" ]] || return 1
  if [[ -f "$dir/hooks.py" && -f "$dir/__init__.py" ]]; then
    return 0
  fi
  for hook in "$dir"/*/hooks.py; do
    [[ -f "$hook" ]] || continue
    if [[ -f "$(dirname "$hook")/__init__.py" ]]; then
      warn "app uses nested Frappe package structure: $(app_name_from_dir "$dir")"
      return 0
    fi
  done
  return 1
}

has_package_metadata() {
  local dir="$1"
  [[ -f "$dir/pyproject.toml" || -f "$dir/setup.py" || -f "$dir/setup.cfg" ]]
}

ensure_app_importable() {
  local app="$1"
  local app_dir="$BENCH_DIR/apps/$app"

  [[ -d "$app_dir" ]] || return 1
  if [[ ! "$app" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
    warn "app name is not a valid Python import name, not selectable: $app"
    return 1
  fi

  if has_package_metadata "$app_dir"; then
    if ! (cd "$BENCH_DIR" && ./env/bin/python -m pip install -e "apps/$app" >/dev/null); then
      warn "editable install failed; app will not be selectable: $app"
      return 1
    fi
  else
    warn "No Python package metadata found. App may not be importable. Please add pyproject.toml/setup.py or correct package structure: $app"
  fi

  if ! "$BENCH_DIR/env/bin/python" -c "import importlib; importlib.import_module('$app')" >/dev/null 2>&1; then
    warn "import test failed; app will not be selectable: $app"
    return 1
  fi

  return 0
}

ensure_app_in_apps_txt() {
  local app="$1"
  local apps_txt="$BENCH_DIR/sites/apps.txt"
  local last_char=""

  [[ -f "$apps_txt" ]] || {
    warn "bench apps.txt missing; creating: $apps_txt"
    : >"$apps_txt"
  }

  if grep -Fxq "$app" "$apps_txt"; then
    info "app already registered in sites/apps.txt: $app"
    return 0
  fi

  if [[ -s "$apps_txt" ]]; then
    last_char="$(tail -c 1 "$apps_txt" 2>/dev/null || true)"
    [[ -z "$last_char" ]] || printf '\n' >>"$apps_txt"
  fi

  printf '%s\n' "$app" >>"$apps_txt"
  ok "registered app in sites/apps.txt: $app"
}

discover_source_apps() {
  [[ -d "$APPS_SRC" ]] || return 0
  local dir name
  for dir in "$APPS_SRC"/*; do
    [[ -d "$dir" ]] || continue
    name="$(app_name_from_dir "$dir")"
    is_system_app "$name" && continue
    if valid_custom_app_dir "$dir"; then
      printf '%s\n' "$name"
    else
      warn "invalid custom app folder, skipping: $name"
    fi
  done | sort
}

discover_bench_custom_apps() {
  [[ -d "$BENCH_DIR/apps" ]] || return 0
  local dir name
  for dir in "$BENCH_DIR/apps"/*; do
    [[ -d "$dir" ]] || continue
    name="$(app_name_from_dir "$dir")"
    is_system_app "$name" && continue
    valid_custom_app_dir "$dir" || continue
    printf '%s\n' "$name"
  done | sort
}

copy_custom_apps() {
  validate_runtime
  if [[ ! -d "$APPS_SRC" ]]; then
    warn "apps source folder missing: $APPS_SRC"
    return 0
  fi

  section "Sync apps"
  local app src dest
  while IFS= read -r app; do
    [[ -n "$app" ]] || continue
    src="$APPS_SRC/$app"
    dest="$BENCH_DIR/apps/$app"
    if [[ -e "$dest" ]]; then
      warn "App already exists, skipping copy: $app"
    else
      info "copying app: $app"
      run cp -a "$src" "$dest"
    fi
  done < <(discover_source_apps)
}

prepare_app_imports() {
  validate_runtime
  local app app_dir
  while IFS= read -r app; do
    [[ -n "$app" ]] || continue
    app_dir="$BENCH_DIR/apps/$app"
    [[ -d "$app_dir" ]] || continue
    if ensure_app_importable "$app"; then
      ensure_app_in_apps_txt "$app"
    fi
  done < <(discover_bench_custom_apps)
}

discover_importable_bench_custom_apps() {
  local app
  while IFS= read -r app; do
    [[ -n "$app" ]] || continue
    if ensure_app_importable "$app"; then
      ensure_app_in_apps_txt "$app" >&2
      printf '%s\n' "$app"
    fi
  done < <(discover_bench_custom_apps)
}

ensure_custom_app_assets() {
  validate_runtime
  mkdir -p "$BENCH_DIR/sites/assets"

  local app public_dir asset_link target
  while IFS= read -r app; do
    [[ -n "$app" ]] || continue
    public_dir="$BENCH_DIR/apps/$app/public"
    asset_link="$BENCH_DIR/sites/assets/$app"
    [[ -d "$public_dir" ]] || continue

    if [[ -L "$asset_link" ]]; then
      target="$(readlink "$asset_link")"
      if [[ "$target" == "$public_dir" ]]; then
        info "asset link ok: $app"
      else
        info "updating asset symlink: $app"
        run ln -sfn "$public_dir" "$asset_link"
      fi
    elif [[ -e "$asset_link" ]]; then
      warn "asset path exists and is not a symlink, leaving untouched: $asset_link"
    else
      run ln -s "$public_dir" "$asset_link"
    fi
  done < <(discover_bench_custom_apps)
}

sync_custom_apps() {
  copy_custom_apps
  prepare_app_imports
  ensure_custom_app_assets
  ok "apps sync complete"
}

random_hex() {
  if have_cmd openssl; then
    openssl rand -hex "$1"
  else
    date +%s%N | sha256sum | cut -c "1-$(("$1" * 2))"
  fi
}

strong_password() {
  if have_cmd openssl; then
    openssl rand -base64 42 | tr -d '\n' | cut -c 1-40
  else
    warn "openssl is missing; using a weaker random fallback"
    printf '%s%s' "$(date +%s%N)" "$RANDOM" | sha256sum | cut -c 1-40
  fi
}

make_db_name() {
  printf '_%s' "$(random_hex 8)"
}

make_db_password() {
  strong_password
}

sql_quote() {
  printf "%s" "$1" | sed "s/'/''/g"
}

sql_identifier() {
  printf "%s" "$1" | sed 's/`/``/g'
}

safe_db_name() {
  [[ -n "$1" && "$1" =~ ^[A-Za-z0-9_]+$ ]]
}

create_database_sql() {
  local db_name="$1"
  local db_password="$2"
  local quoted_pass quoted_user ident
  quoted_pass="$(sql_quote "$db_password")"
  quoted_user="$(sql_quote "$db_name")"
  ident="$(sql_identifier "$db_name")"
  cat <<SQL
CREATE DATABASE IF NOT EXISTS \`$ident\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '$quoted_user'@'localhost' IDENTIFIED BY '$quoted_pass';
ALTER USER '$quoted_user'@'localhost' IDENTIFIED BY '$quoted_pass';
GRANT ALL PRIVILEGES ON \`$ident\`.* TO '$quoted_user'@'localhost';
FLUSH PRIVILEGES;
SQL
}

drop_database_sql() {
  local db_name="$1"
  local quoted_user ident
  quoted_user="$(sql_quote "$db_name")"
  ident="$(sql_identifier "$db_name")"
  cat <<SQL
DROP DATABASE IF EXISTS \`$ident\`;
DROP USER IF EXISTS '$quoted_user'@'localhost';
FLUSH PRIVILEGES;
SQL
}

mariadb_socket_auth_available() {
  need_sudo || return 1
  "${SUDO[@]}" mariadb -e "SELECT 1;" >/dev/null 2>&1
}

create_database_with_sudo() {
  local db_name="$1"
  local db_password="$2"
  mariadb_socket_auth_available || return 1
  info "creating MariaDB database/user via sudo socket auth"
  create_database_sql "$db_name" "$db_password" | "${SUDO[@]}" mariadb
}

create_database_with_credentials() {
  local db_name="$1"
  local db_password="$2"
  local db_admin_user db_admin_password

  warn "sudo MariaDB socket auth failed or is unavailable."
  read -r -p "MariaDB admin user [root]: " db_admin_user
  db_admin_user="${db_admin_user:-root}"
  read -r -s -p "MariaDB password for $db_admin_user: " db_admin_password
  printf '\n'

  if [[ -n "$db_admin_password" ]]; then
    create_database_sql "$db_name" "$db_password" | MYSQL_PWD="$db_admin_password" mariadb -u "$db_admin_user"
  else
    create_database_sql "$db_name" "$db_password" | mariadb -u "$db_admin_user"
  fi
}

create_database_and_user() {
  local db_name="$1"
  local db_password="$2"
  have_cmd mariadb || die "mariadb client command not found"
  safe_db_name "$db_name" || die "generated DB name is invalid: $db_name"

  if create_database_with_sudo "$db_name" "$db_password"; then
    ok "database prepared: $db_name"
    return 0
  fi

  create_database_with_credentials "$db_name" "$db_password" || die "could not prepare MariaDB database/user"
  ok "database prepared: $db_name"
}

drop_database_with_sudo() {
  local db_name="$1"
  safe_db_name "$db_name" || {
    warn "refusing to drop unsafe or empty database name: $db_name"
    return 1
  }
  mariadb_socket_auth_available || return 1
  info "dropping MariaDB database/user via sudo socket auth: $db_name"
  drop_database_sql "$db_name" | "${SUDO[@]}" mariadb
}

drop_database_with_credentials() {
  local db_name="$1"
  local db_admin_user db_admin_password
  safe_db_name "$db_name" || {
    warn "refusing to drop unsafe or empty database name: $db_name"
    return 1
  }

  read -r -p "MariaDB admin user [root]: " db_admin_user
  db_admin_user="${db_admin_user:-root}"
  read -r -s -p "MariaDB password for $db_admin_user: " db_admin_password
  printf '\n'

  if [[ -n "$db_admin_password" ]]; then
    drop_database_sql "$db_name" | MYSQL_PWD="$db_admin_password" mariadb -u "$db_admin_user"
  else
    drop_database_sql "$db_name" | mariadb -u "$db_admin_user"
  fi
}

drop_database_and_user() {
  local db_name="$1"
  local answer

  if drop_database_with_sudo "$db_name"; then
    ok "database and DB user dropped: $db_name"
    return 0
  fi

  warn "sudo MariaDB socket auth failed or is unavailable."
  read -r -p "Try MariaDB admin credentials instead? y/N: " answer
  case "${answer:-}" in
    y|Y|yes|YES)
      drop_database_with_credentials "$db_name" || return 1
      ok "database and DB user dropped: $db_name"
      ;;
    *)
      warn "database was not dropped: $db_name"
      return 1
      ;;
  esac
}

read_optional_secret_with_confirm() {
  local -n _secret="$1"
  local prompt="$2"
  local confirm_prompt="$3"
  local first second

  while true; do
    read -r -s -p "$prompt" first
    printf '\n'
    if [[ -z "$first" ]]; then
      _secret=""
      return 0
    fi

    read -r -s -p "$confirm_prompt" second
    printf '\n'
    if [[ "$first" == "$second" ]]; then
      _secret="$first"
      return 0
    fi
    warn "passwords did not match; try again or press Enter to auto-generate"
  done
}

read_admin_password() {
  if [[ -n "${FRAPPE_ADMIN_PASSWORD:-}" ]]; then
    ADMIN_PASSWORD="$FRAPPE_ADMIN_PASSWORD"
    ADMIN_PASSWORD_SOURCE="FRAPPE_ADMIN_PASSWORD environment variable"
    if [[ "$ADMIN_PASSWORD" == "admin" ]]; then
      warn "FRAPPE_ADMIN_PASSWORD is set to 'admin'; consider using a stronger password."
    fi
    return 0
  fi

  read_optional_secret_with_confirm ADMIN_PASSWORD \
    "Administrator password (press Enter to auto-generate): " \
    "Confirm Administrator password: "
  if [[ -z "$ADMIN_PASSWORD" ]]; then
    ADMIN_PASSWORD="$(strong_password)"
    ADMIN_PASSWORD_SOURCE="auto-generated"
    ok "Administrator password auto-generated; it will be saved to .secrets/sites/ after site creation"
  else
    ADMIN_PASSWORD_SOURCE="entered manually"
  fi
}

read_site_db_password() {
  local -n _password="$1"
  local -n _source="$2"

  read_optional_secret_with_confirm "$1" \
    "Site DB password (press Enter to auto-generate): " \
    "Confirm Site DB password: "
  if [[ -z "$_password" ]]; then
    _password="$(make_db_password)"
    _source="auto-generated"
    ok "Site DB password auto-generated; it will be saved to .secrets/sites/ after site creation"
  else
    _source="entered manually"
  fi
}

read_site_name() {
  local -n _site="$1"
  local raw lowered
  while true; do
    read -r -p "Site name (example site.local): " raw
    if [[ -z "$raw" ]]; then
      warn "site name is required"
      continue
    fi
    if [[ "$raw" =~ [[:space:]] ]]; then
      warn "site name must not contain spaces"
      continue
    fi
    lowered="${raw,,}"
    if [[ "$raw" != "$lowered" ]]; then
      warn "Site names must be lowercase. Using $lowered"
    fi
    if [[ "$lowered" != *.* ]]; then
      warn "site name usually includes a suffix, example site.local"
    fi
    if [[ -d "$BENCH_DIR/sites/$lowered" ]]; then
      warn "site already exists: $lowered"
      continue
    fi
    _site="$lowered"
    return 0
  done
}

select_apps() {
  local -n _out="$1"
  local available idx choice token
  mapfile -t available < <(discover_importable_bench_custom_apps)
  _out=()

  if [[ "${#available[@]}" -eq 0 ]]; then
    warn "no importable custom apps available; site will use only Frappe"
    return 0
  fi

  printf '\nSelect apps for this site:\n'
  local i
  for i in "${!available[@]}"; do
    printf '  %d) %s\n' "$((i + 1))" "${available[$i]}"
  done
  printf '  a) all apps\n'
  printf '  n) no custom apps\n'

  while true; do
    read -r -p "Choose app numbers, comma-separated [1]: " choice
    choice="${choice:-1}"
    choice="${choice//[[:space:]]/}"

    if [[ "$choice" == "a" || "$choice" == "A" ]]; then
      _out=("${available[@]}")
      printf 'Selected apps: %s\n' "$(join_by ', ' "${_out[@]}")"
      return 0
    fi

    if [[ "$choice" == "n" || "$choice" == "N" ]]; then
      _out=()
      warn "no custom apps selected"
      return 0
    fi

    _out=()
    IFS=',' read -r -a parts <<<"$choice"
    local valid=1 seen=" "
    for token in "${parts[@]}"; do
      if [[ "$token" =~ ^[0-9]+$ ]]; then
        idx=$((token - 1))
        if (( idx >= 0 && idx < ${#available[@]} )); then
          if [[ "$seen" != *" ${available[$idx]} "* ]]; then
            _out+=("${available[$idx]}")
            seen="$seen${available[$idx]} "
          fi
        else
          valid=0
        fi
      else
        valid=0
      fi
    done

    if [[ "$valid" -eq 1 ]]; then
      printf 'Selected apps: %s\n' "$(join_by ', ' "${_out[@]}")"
      return 0
    fi

    warn "invalid app selection; use numbers like 1 or 1,2, or a/n"
  done
}

site_config_value() {
  local site="$1"
  local key="$2"
  local site_config="$BENCH_DIR/sites/$site/site_config.json"
  [[ -f "$site_config" ]] || return 1
  "$BENCH_DIR/env/bin/python" -c 'import json, sys
with open(sys.argv[1], encoding="utf-8") as f:
    data = json.load(f)
value = data.get(sys.argv[2], "")
print("" if value is None else value)
' "$site_config" "$key"
}

archive_site_folder() {
  local site="$1"
  local out_var="$2"
  local site_dir="$BENCH_DIR/sites/$site"
  local archive_dir="$BENCH_DIR/sites/archived"
  local archive_dest="$archive_dir/$site.deleted-$(date +%Y%m%d-%H%M%S)"

  [[ -d "$site_dir" ]] || {
    warn "site folder not found, cannot archive: $site_dir"
    return 1
  }

  mkdir -p "$archive_dir"
  if [[ -e "$archive_dest" ]]; then
    archive_dest="$archive_dest.$$"
  fi

  info "[RUN] mv $site_dir $archive_dest"
  mv "$site_dir" "$archive_dest"
  printf -v "$out_var" '%s' "$archive_dest"
}

remove_hosts_entry() {
  local site="$1"
  local tmp

  if ! need_sudo; then
    warn "sudo unavailable; hosts entry was not removed"
    return 1
  fi

  tmp="$(mktemp -t frappe-hosts.XXXXXX)"
  awk -v site="$site" '
    function has_site() {
      for (i = 1; i <= NF; i++) {
        if ($i == site) {
          return 1
        }
      }
      return 0
    }
    index($0, "# managed-by-frappe-custom-installer") && has_site() { next }
    { print }
  ' /etc/hosts >"$tmp"

  if cmp -s "$tmp" /etc/hosts; then
    warn "no managed /etc/hosts entry found for $site"
    rm -f "$tmp"
    return 0
  fi

  "${SUDO[@]}" cp "$tmp" /etc/hosts
  rm -f "$tmp"
  ok "removed managed /etc/hosts entry for $site"
}

rollback_new_site_prompt() {
  local site="$1"
  local db_name="$2"
  local answer archive_path="" db_dropped="no"

  read -r -p "Rollback newly created site? y/N: " answer
  case "${answer:-}" in
    y|Y|yes|YES)
      if [[ -n "$db_name" ]]; then
        drop_database_and_user "$db_name" && db_dropped="yes"
      fi
      if [[ -d "$BENCH_DIR/sites/$site" ]]; then
        archive_site_folder "$site" archive_path || warn "rollback archive failed; inspect site manually: $site"
      fi
      append_note_secret "Site creation failed / rolled back" \
        "Site: $site" \
        "DB name: ${db_name:-unknown}" \
        "DB dropped: $db_dropped" \
        "Archive path: ${archive_path:-none}"
      ;;
    *)
      warn "site kept for inspection: $site"
      append_note_secret "Site creation failed / kept" \
        "Site: $site" \
        "DB name: ${db_name:-unknown}" \
        "DB dropped: no"
      ;;
  esac
}

hosts_entry_exists() {
  local site="$1"
  awk -v site="$site" '
    $1 == "127.0.0.1" {
      for (i = 2; i <= NF; i++) {
        if ($i == site) {
          found = 1
        }
      }
    }
    END { exit found ? 0 : 1 }
  ' /etc/hosts
}

is_wsl() {
  grep -qiE 'microsoft|wsl' /proc/version 2>/dev/null || grep -qiE 'microsoft|wsl' /proc/sys/kernel/osrelease 2>/dev/null
}

print_wsl_windows_hosts_hint() {
  local site="$1"

  is_wsl || return 0

  printf '\n'
  warn "WSL detected. Linux /etc/hosts is not always enough for Windows browser custom domains."
  warn "localhost usually works from Windows:"
  printf '  http://localhost:8000\n\n'
  warn "For custom domain access from Windows browser, add this line to Windows hosts:"
  printf '  127.0.0.1 %s\n\n' "$site"
  printf 'PowerShell as Administrator example:\n'
  printf "  Start-Process powershell -Verb runAs -ArgumentList \"Add-Content -Path C:\\Windows\\System32\\drivers\\etc\\hosts -Value '127.0.0.1 %s'\"\n" "$site"
  printf '\n'
}

ensure_hosts_entry() {
  local site="$1"
  local line="127.0.0.1 $site # managed-by-frappe-custom-installer"

  print_wsl_windows_hosts_hint "$site"

  if hosts_entry_exists "$site"; then
    info "Linux /etc/hosts entry already exists for $site"
    return 0
  fi

  warn "missing Linux /etc/hosts entry for $site"
  warn "command: echo '$line' | sudo tee -a /etc/hosts"

  local answer
  read -r -p "Add Linux /etc/hosts entry now? y/N: " answer
  case "${answer:-}" in
    y|Y|yes|YES)
      if need_sudo; then
        printf '%s\n' "$line" | "${SUDO[@]}" tee -a /etc/hosts >/dev/null || warn "could not update /etc/hosts"
      else
        warn "sudo unavailable; run manually: echo '$line' | sudo tee -a /etc/hosts"
      fi
      ;;
    *)
      warn "Linux hosts entry not added; run manually if browser cannot resolve $site"
      ;;
  esac
}

print_site_summary() {
  local site="$1"
  section "Site Summary"
  printf 'Site URL: http://%s:8000\n' "$site"
  printf 'Admin user: Administrator\n'
  printf 'Admin password: %s (saved to .secrets/sites/)\n' "$ADMIN_PASSWORD_SOURCE"
  if ! bench_run --site "$site" list-apps; then
    warn "could not read installed apps for $site"
  fi
  ok "Run ./start.sh to start all sites."
}

create_site_once() {
  section "New Site"
  sync_custom_apps

  local site selected_apps=()
  read_site_name site
  read_admin_password
  select_apps selected_apps

  local db_name db_password db_password_source
  db_name="$(make_db_name)"
  read_site_db_password db_password db_password_source
  create_database_and_user "$db_name" "$db_password"

  info "creating site: $site"
  info "[RUN] bench new-site $site --admin-password *** --db-name $db_name --db-password *** --no-setup-db"
  if ! (cd "$BENCH_DIR" && bench new-site "$site" \
    --admin-password "$ADMIN_PASSWORD" \
    --db-name "$db_name" \
    --db-password "$db_password" \
    --no-setup-db); then
    err "site creation failed: $site"
    rollback_new_site_prompt "$site" "$db_name"
    return 1
  fi

  if ! ensure_bench_dev_services; then
    err "bench services did not start; migrate/install cannot continue safely"
    rollback_new_site_prompt "$site" "$db_name"
    return 1
  fi

  local app failed=0
  for app in "${selected_apps[@]}"; do
    info "installing app on $site: $app"
    if bench_run --site "$site" install-app "$app"; then
      ok "app installed: $app"
    else
      err "app install failed: $app"
      failed=1
    fi
  done

  if (( failed == 1 )); then
    rollback_new_site_prompt "$site" "$db_name"
    return 1
  fi

  if ! ensure_bench_dev_services; then
    err "bench services are not running before migrate"
    rollback_new_site_prompt "$site" "$db_name"
    return 1
  fi

  if ! bench_run --site "$site" migrate; then
    err "migrate failed for $site"
    rollback_new_site_prompt "$site" "$db_name"
    return 1
  fi

  ensure_hosts_entry "$site"
  append_site_secret "$site" "$ADMIN_PASSWORD" "$ADMIN_PASSWORD_SOURCE" "$db_name" "$db_password" "$db_password_source" "$(join_by ', ' "${selected_apps[@]}")"
  print_site_summary "$site"
}

new_site_flow() {
  while true; do
    create_site_once || warn "new site flow ended with errors; check log: $RUN_LOG"
    local again
    read -r -p "Create another site? y/N: " again
    case "${again:-}" in
      y|Y|yes|YES) continue ;;
      *)
        info "new site flow closed"
        return 0
        ;;
    esac
  done
}

select_site() {
  local -n _selected="$1"
  local sites choice idx
  mapfile -t sites < <(site_names)
  _selected=""
  if [[ "${#sites[@]}" -eq 0 ]]; then
    warn "no valid sites found"
    return 1
  fi

  printf '\nAvailable sites:\n'
  local i
  for i in "${!sites[@]}"; do
    printf '  %d) %s\n' "$((i + 1))" "${sites[$i]}"
  done

  while true; do
    read -r -p "Choose site: " choice
    choice="${choice//[[:space:]]/}"
    [[ "$choice" =~ ^[0-9]+$ ]] || {
      warn "invalid site selection"
      continue
    }
    idx=$((choice - 1))
    if (( idx >= 0 && idx < ${#sites[@]} )); then
      _selected="${sites[$idx]}"
      return 0
    fi
    warn "invalid site selection"
  done
}

delete_site_flow() {
  section "Delete Site"
  validate_runtime
  local site confirm db_name delete_db archive_path="" db_dropped="no" hosts_removed="no" answer
  select_site site || return 0
  [[ -n "$site" ]] || return 0

  db_name="$(site_config_value "$site" db_name 2>/dev/null || true)"

  warn "this will archive site folder: $BENCH_DIR/sites/$site"
  if [[ -n "$db_name" ]]; then
    warn "detected site database: $db_name"
  else
    warn "could not read db_name from site_config.json; database will not be dropped automatically"
  fi
  read -r -p "Type the site name to delete: " confirm
  if [[ "$confirm" != "$site" ]]; then
    warn "delete cancelled"
    return 0
  fi

  read -r -p "Delete database and DB user too? Y/n: " delete_db
  case "${delete_db:-Y}" in
    y|Y|yes|YES)
      if [[ -n "$db_name" ]]; then
        if drop_database_and_user "$db_name"; then
          db_dropped="yes"
        else
          warn "database was not dropped; continuing with site archive"
        fi
      else
        warn "database was not dropped because db_name is unavailable"
      fi
      ;;
    *)
      warn "database and DB user kept"
      ;;
  esac

  archive_site_folder "$site" archive_path || die "could not archive site folder: $site"

  read -r -p "Remove /etc/hosts entry? y/N: " answer
  case "${answer:-}" in
    y|Y|yes|YES)
      if remove_hosts_entry "$site"; then
        hosts_removed="yes"
      fi
      ;;
    *)
      warn "hosts entry kept"
      ;;
  esac

  append_note_secret "Site deleted / archived" \
    "Site: $site" \
    "DB name: ${db_name:-unknown}" \
    "DB dropped: $db_dropped" \
    "Hosts entry removed: $hosts_removed" \
    "Archive path: $archive_path"

  remove_site_secret "$site"
  ok "site archived: $archive_path"
}

list_sites_and_apps() {
  section "Sites and Apps"
  validate_runtime
  local sites site
  mapfile -t sites < <(site_names)
  if [[ "${#sites[@]}" -eq 0 ]]; then
    warn "no valid sites found"
    return 0
  fi

  for site in "${sites[@]}"; do
    printf '\n- %s\n' "$site"
    if [[ "$site" != "${site,,}" ]]; then
      warn "Site folder contains uppercase. Browsers usually send lowercase hostnames. Rename site folder/config to lowercase: $site"
    fi
    if ! bench_run --site "$site" list-apps; then
      warn "could not list apps for $site"
    fi
  done
}

uppercase_site_names() {
  local site
  while IFS= read -r site; do
    [[ -n "$site" ]] || continue
    if [[ "$site" != "${site,,}" ]]; then
      printf '%s\n' "$site"
    fi
  done < <(site_names)
}

select_uppercase_site() {
  local -n _selected="$1"
  local sites choice idx
  mapfile -t sites < <(uppercase_site_names)
  _selected=""

  if [[ "${#sites[@]}" -eq 0 ]]; then
    warn "no uppercase site folders found"
    return 1
  fi

  printf '\nUppercase site folders:\n'
  local i
  for i in "${!sites[@]}"; do
    printf '  %d) %s -> %s\n' "$((i + 1))" "${sites[$i]}" "${sites[$i],,}"
  done

  while true; do
    read -r -p "Choose site to rename: " choice
    choice="${choice//[[:space:]]/}"
    [[ "$choice" =~ ^[0-9]+$ ]] || {
      warn "invalid site selection"
      continue
    }
    idx=$((choice - 1))
    if (( idx >= 0 && idx < ${#sites[@]} )); then
      _selected="${sites[$idx]}"
      return 0
    fi
    warn "invalid site selection"
  done
}

rename_site_to_lowercase_flow() {
  section "Rename Site to Lowercase"
  validate_runtime

  local old_site new_site confirm
  select_uppercase_site old_site || return 0
  [[ -n "$old_site" ]] || return 0
  new_site="${old_site,,}"

  if [[ -e "$BENCH_DIR/sites/$new_site" ]]; then
    die "lowercase target already exists: $BENCH_DIR/sites/$new_site"
  fi

  warn "Bench should be stopped before renaming a site folder."
  warn "This will rename: $old_site -> $new_site"
  warn "The database name will not be changed."
  read -r -p "Type '$old_site -> $new_site' to confirm: " confirm
  if [[ "$confirm" != "$old_site -> $new_site" ]]; then
    warn "rename cancelled"
    return 0
  fi

  info "[RUN] mv $BENCH_DIR/sites/$old_site $BENCH_DIR/sites/$new_site"
  mv "$BENCH_DIR/sites/$old_site" "$BENCH_DIR/sites/$new_site"
  ensure_hosts_entry "$new_site"

  append_note_secret "Site renamed to lowercase" \
    "Old site: $old_site" \
    "New site: $new_site" \
    "Database name changed: no"

  if ! bench_run --site "$new_site" list-apps; then
    warn "bench could not read apps after rename. If needed, manually revert:"
    warn "  mv '$BENCH_DIR/sites/$new_site' '$BENCH_DIR/sites/$old_site'"
  fi

  ok "site renamed: $old_site -> $new_site"
}

site_menu() {
  ensure_secrets_file
  validate_runtime
  while true; do
    printf '\n'
    printf '====================\n'
    printf ' Site Setup Manager\n'
    printf '====================\n'
    printf 'Bench: %s\n' "$BENCH_DIR"
    printf 'Log:   %s\n\n' "$RUN_LOG"
    printf '1) New Site\n'
    printf '2) Delete Site\n'
    printf '3) List Sites and Apps\n'
    printf '4) Sync apps\n'
    printf '5) Rename Site to Lowercase\n'
    printf '6) Repair Secrets\n'
    printf '7) Exit\n'
    read -r -p "Choose: " choice
    case "${choice:-}" in
      1) new_site_flow ;;
      2) delete_site_flow ;;
      3) list_sites_and_apps ;;
      4) sync_custom_apps ;;
      5) rename_site_to_lowercase_flow ;;
      6) repair_secrets ;;
      7) info "bye"; exit 0 ;;
      *) warn "invalid option" ;;
    esac
  done
}

site_menu "$@"
